export const tableHeadings = [
    {title: 'Conservancy', name: 'conservancy'},
    {title: 'County', name: 'county'},
    {title: 'Station', name: 'forest_station'},
    {title: 'Subcompartment', name: 'subcompartment'},
    {title: 'Species', name: 'species'},
    {title: 'Xcordinate', name: 'xcordinate'},
    {title: 'Ycordinate', name: 'ycordinate'},
    {title: 'Area', name: 'area'},
    {title: 'Planting Year', name: 'planting_year'},
    {title: 'Density', name: 'density'},
    {title: 'MDBH', name: 'mdbh'},
    {title: 'MHT', name: 'mht'},
    {title: 'Age', name: 'age'},
    {title: 'Remarks', name: 'remarks'},
    {title: 'Station Id', name: 'station_id'},
    {title: 'County Id', name: 'county_id'},
    {title: 'Station Name', name: 'station_name'},
    {title: 'Conservancy', name: 'conservancy'},
]